apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: exemplo
spec:
  acme:
    email: leonardomichalskim@gmail.com
    privateKeySecretRef:
      name: issuer-exemplo
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
