apiVersion: v1
kind: Service
metadata:
  name: exemplo-postgres
  # Labels do Service
  labels:
    app: exemplo-postgres
spec:
  # Especifica a qual/quais Pods o Service se refere (nao Deployment!!)
  selector:
    app: exemplo-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    name: postgres
