kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: aula-gces
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"        
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
#networking:
#  apiServerAddress: 192.168.0.60
#  apiServerPort: 6443
